import type { Metadata } from 'next';
import { Inter, Newsreader } from 'next/font/google';

import './global.css';
import Footer from './_noPages/views/footer/Footer';

const interFont = Inter({
  subsets: ['latin'],
  weight: ['300', '400', '600', '700'],
  variable: '--font-interFont',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${interFont.variable}`}>
        {/* <header>
          <Header />
        </header> */}

        <main>{children}</main>
        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  );
}

//Usar variables css en global.css en vez de un config y styles. Body tambien
